SELECT
      C.AUTHOR_ID
    , C.AUTHOR_NAME
    , B.CATEGORY
    , SUM(A.SALES * B.PRICE) AS TOTAL_PRICE
FROM
    BOOK_SALES A
LEFT OUTER JOIN
    BOOK B
ON
    A.BOOK_ID = B.BOOK_ID
LEFT OUTER JOIN
    AUTHOR C
ON
    B.AUTHOR_ID = C.AUTHOR_ID
WHERE
    TO_CHAR(A.SALES_DATE, 'YYYYMM') = '202201'
GROUP BY
    C.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY
ORDER BY
    C.AUTHOR_ID, B.CATEGORY DESC