SELECT
      CAR_ID
    , ROUND(AVG(AVERAGE_DURATION), 1) AS AVERAGE_DURATION
FROM
    (
        SELECT
              CAR_ID
            , END_DATE - START_DATE AS AVERAGE_DURATION
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) A
GROUP BY
    CAR_ID
HAVING
    ROUND(AVG(AVERAGE_DURATION), 1) >= 7
ORDER BY
    AVERAGE_DURATION DESC, CAR_ID DESC