SELECT
      A.APNT_NO
    , B.PT_NAME
    , A.PT_NO
    , A.MCDP_CD
    , C.DR_NAME
    , A.APNT_YMD
FROM
    APPOINTMENT A
LEFT OUTER JOIN
    PATIENT B
ON
    A.PT_NO = B.PT_NO
LEFT OUTER JOIN
    DOCTOR C
ON
    A.MDDR_ID = C.DR_ID
WHERE
    TO_CHAR(A.APNT_YMD, 'YYYYMMDD') = '20220413'
AND
    A.APNT_CNCL_YN = 'N'
AND
    A.MCDP_CD = 'CS'
ORDER BY
    A.APNT_YMD 